SELECT * FROM person WHERE age BETWEEN 18 AND 26;
SELECT * FROM person WHERE age NOT BETWEEN 18 AND 26;
SELECT * FROM person WHERE id BETWEEN 2 AND 6;
SELECT * FROM person WHERE name BETWEEN "a" AND "t";
